import Joi from 'joi';
import { InstrumentStatus } from './instrument.model';

export const createInstrumentSchema = Joi.object({
  name: Joi.string().required(),
  code: Joi.string().optional(), // Autogenerated if not provided
  serialNumber: Joi.string().required(),
  make: Joi.string().required(),
  model: Joi.string().required(),
  lastCalibrationDate: Joi.date().required(),
  calibrationDueDate: Joi.date().required(),
  certificateNumber: Joi.string().required(),
  accuracy: Joi.string().allow('', null).optional(),
  range: Joi.string().allow('', null).optional(),
  status: Joi.string().valid(...Object.values(InstrumentStatus)).default(InstrumentStatus.ACTIVE),
  notes: Joi.string().allow('', null).optional(),
  availableTestTypeIds: Joi.array().items(Joi.string()).optional(),
}).unknown(true);

export const updateInstrumentSchema = createInstrumentSchema.fork(
  Object.keys(createInstrumentSchema.describe().keys),
  (schema) => schema.optional()
);
