import { Schema, model, Document, Types } from 'mongoose';

export enum EquipmentStatus {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  MAINTENANCE = 'maintenance',
}

export interface IEquipment extends Omit<Document, 'model'> {
  name: string;
  code: string; // Autogenerated unique ID/QR
  equipmentType?: 'equipment' | 'area';
  serialNumber?: string;
  make?: string;
  model?: string;
  area?: string; // Optional, populated during service
  validationFrequencyDays: number;
  calibrationFrequencyDays: number;
  lastValidationDate?: Date;
  nextValidationDate?: Date;
  lastCalibrationDate?: Date;
  nextCalibrationDate?: Date;
  status: EquipmentStatus;
  notes?: string;
  organizationId?: Types.ObjectId | null;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

const equipmentSchema = new Schema<IEquipment>(
  {
    name: { type: String, required: true, trim: true },
    code: { type: String, required: true, trim: true },
    equipmentType: { type: String, enum: ['equipment', 'area'], default: 'equipment' },
    serialNumber: { type: String, trim: true, default: '' },
    make: { type: String, trim: true, default: '' },
    model: { type: String, trim: true, default: '' },
    area: { type: String, trim: true },
    validationFrequencyDays: { type: Number, default: 365 },
    calibrationFrequencyDays: { type: Number, default: 365 },
    lastValidationDate: { type: Date },
    nextValidationDate: { type: Date },
    lastCalibrationDate: { type: Date },
    nextCalibrationDate: { type: Date },
    status: {
      type: String,
      enum: Object.values(EquipmentStatus),
      default: EquipmentStatus.ACTIVE,
    },
    notes: { type: String, trim: true },
    organizationId: { type: Schema.Types.ObjectId, ref: 'Organization', default: null, index: true },
    createdBy: { type: String, required: true },
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_doc, ret: Record<string, unknown>) => {
        ret.id = (ret._id as { toString(): string }).toString();
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  },
);

equipmentSchema.index({ organizationId: 1, code: 1 }, { unique: true });

export const EquipmentModel = model<IEquipment>('Equipment', equipmentSchema);
