import Joi from 'joi';
import { EquipmentStatus } from './equipment.model';

export const createEquipmentSchema = Joi.object({
  name: Joi.string().required(),
  code: Joi.string().optional(), // Autogenerated if not provided
  serialNumber: Joi.string().required(),
  make: Joi.string().required(),
  model: Joi.string().required(),
  validationFrequencyDays: Joi.number().default(365),
  calibrationFrequencyDays: Joi.number().default(365),
  status: Joi.string().valid(...Object.values(EquipmentStatus)).default(EquipmentStatus.ACTIVE),
  notes: Joi.string().allow('', null).optional(),
}).unknown(true);

export const updateEquipmentSchema = createEquipmentSchema.fork(
  Object.keys(createEquipmentSchema.describe().keys),
  (schema) => schema.optional()
);
